#!/usr/bin/env bash
# Build the browser bundle.
#
#   tools/build_web.sh            build web/dist, ready to publish
#   tools/build_web.sh --serve    build the wasm and assets, then `vite dev`
#
# Produces web/pkg (the wasm module and its JS glue) and web/public/{data,vendor}
# (the sample datasets and sql.js). All three are generated, all three are
# gitignored: the repo holds sources, and anything a build can reproduce does
# not belong in it.
#
# SITE_BASE is the path the site will be served from. GitHub Pages serves this
# repository at /<repo>/, so the workflow sets it; unset means the root, which
# is what a local build wants.
set -euo pipefail
cd "$(dirname "$0")/.."

command -v wasm-pack >/dev/null || {
  echo "wasm-pack is required: https://rustwasm.github.io/wasm-pack/installer/" >&2
  exit 1
}
command -v npm >/dev/null || {
  echo "npm is required: the page is TypeScript built by Vite" >&2
  exit 1
}

echo "==> building the wasm module"
# `--target web` emits an ES module. Vite bundles it from there, and rewrites
# the `new URL('qe_bg.wasm', import.meta.url)` inside it to a hashed asset.
wasm-pack build crates/wasm --release --target web \
  --out-dir "$PWD/web/pkg" --out-name qe

echo "==> copying sample datasets"
# public/ is copied verbatim into the build output, so these keep the paths the
# page fetches them from.
mkdir -p web/public/data
cp data/*.csv web/public/data/
# A Parquet table with eight row groups, so the storage inspector has zone maps
# to show and lazy decoding to demonstrate. Generated by tools/gen_parquet.py.
if [[ -f tests/parquet/multi_rowgroup.parquet ]]; then
  cp tests/parquet/multi_rowgroup.parquet web/public/data/metrics.parquet
fi

echo "==> fetching sql.js (the benchmark's opponent)"
mkdir -p web/public/vendor
for f in sql-wasm.js sql-wasm.wasm; do
  if [[ ! -f "web/public/vendor/$f" ]]; then
    curl -sSLf --max-time 120 -o "web/public/vendor/$f" \
      "https://cdn.jsdelivr.net/npm/sql.js@${SQLJS_VERSION:-1.13.0}/dist/$f" \
      || { echo "could not fetch $f; the benchmark page will not load" >&2; rm -f "web/public/vendor/$f"; }
  fi
done

# The social card is generated, not hand-drawn, so it stays in step with the
# page's own colours and type. Skipped rather than fatal where Pillow is
# missing: it is a picture, and a build should not fail for want of one.
if [[ ! -f web/public/og-v1.png ]]; then
  if python3 -c "import PIL" 2>/dev/null; then
    echo "==> drawing the social card"
    python3 tools/make_og_card.py
  else
    echo "  (skipped the social card: Pillow is not installed)" >&2
  fi
fi

echo "==> installing node dependencies"
# `npm ci` when the lockfile is authoritative, which it is everywhere except a
# freshly edited package.json.
if [[ -f web/package-lock.json ]]; then
  npm --prefix web ci --silent
else
  npm --prefix web install --silent
fi

size=$(wc -c < web/pkg/qe_bg.wasm)
printf '==> web/pkg/qe_bg.wasm is %s KiB\n' "$((size / 1024))"

if [[ "${1:-}" == "--serve" ]]; then
  echo "==> http://localhost:8137"
  exec npm --prefix web run dev
fi

echo "==> type-checking and bundling"
npm --prefix web run build
echo "==> web/dist is ready"
