#!/usr/bin/env bash
# Build the browser bundle into web/.
#
#   tools/build_web.sh [--serve]
#
# Produces web/pkg (the wasm module and its JS glue) and web/data (the sample
# datasets). Both are generated, both are gitignored: the repo holds sources,
# and anything a build can reproduce does not belong in it.
set -euo pipefail
cd "$(dirname "$0")/.."

command -v wasm-pack >/dev/null || {
  echo "wasm-pack is required: https://rustwasm.github.io/wasm-pack/installer/" >&2
  exit 1
}

echo "==> building the wasm module"
# `--target web` emits an ES module that a plain <script type=module> can load.
# No bundler, no node_modules: the page is four files and a .wasm.
wasm-pack build crates/wasm --release --target web \
  --out-dir "$PWD/web/pkg" --out-name qe

echo "==> copying sample datasets"
mkdir -p web/data
cp data/*.csv web/data/
# A Parquet table with eight row groups, so the storage inspector has zone maps
# to show and lazy decoding to demonstrate. Generated by tools/gen_parquet.py.
if [[ -f tests/parquet/multi_rowgroup.parquet ]]; then
  cp tests/parquet/multi_rowgroup.parquet web/data/metrics.parquet
fi

echo "==> fetching sql.js (the benchmark's opponent)"
mkdir -p web/vendor
for f in sql-wasm.js sql-wasm.wasm; do
  if [[ ! -f "web/vendor/$f" ]]; then
    curl -sSLf --max-time 120 -o "web/vendor/$f" \
      "https://cdn.jsdelivr.net/npm/sql.js@${SQLJS_VERSION:-1.13.0}/dist/$f" \
      || { echo "could not fetch $f; the benchmark page will not load" >&2; rm -f "web/vendor/$f"; }
  fi
done

size=$(wc -c < web/pkg/qe_bg.wasm)
printf '==> web/pkg/qe_bg.wasm is %s KiB\n' "$((size / 1024))"

if [[ "${1:-}" == "--serve" ]]; then
  echo "==> http://localhost:8137"
  exec python3 tools/serve.py 8137
fi
